apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: gauravrehan/discovery-server:0.0.2-SNAPSHOT
          env:
          - name: server.port
            value: "8761"
          ports:
            - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-server-clusterip
spec:
  type: ClusterIP
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-nodeport
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30761
      protocol: TCP
  
