apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: gauravrehan/gateway-service:0.0.1-SNAPSHOT
          env:
          - name: server.port
            value: "8091"
          - name: discovery.server
            value: "discovery-server-clusterip"
          - name: discovery.port
            value: "8761"
          ports:
            - containerPort: 8091


---

apiVersion: v1
kind: Service
metadata:
  name: gateway-server-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway-server
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-server-service
spec:
  type: NodePort
  selector:
    app: gateway-server
  ports:
    - port: 8091
      targetPort: 8091
      nodePort: 30091
      protocol: TCP
  
